version: 2.1

commands:
  run-test:
    steps:
      - checkout
      - restore_cache:
          name: Restore npm Package Data Cache
          keys:
            - v1-dependency-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CIRCLE_JOB }}
            - v1-dependency-cache-
      - run:
          name: Installing Node packages
          command: npm ci
      - save_cache:
          name: Cache npm Package Data
          key: v1-dependency-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - ./node_modules
      - run:
          name: Linting Source
          command: npm run lint
      - run:
          name: Running Tests
          command: npm run test
      - run:
          name: Building Source
          command: npm run build

jobs:
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - run-test

  node-lts:
    docker:
      - image: circleci/node:lts
    steps:
      - run-test

workflows:
  node-run-tests:
    jobs:
      - node-latest
      - node-lts
  version: 2
